### ISSUE TITLE
Regression in Hugo

### ISSUE THREAD

**Issue by bep** [spf13/afero#18]
Hugo builds started to fail recently due to an issue with Afero:

```
links
--- PASS: TestSiteInfoPermalinks (0.00s)
=== RUN TestSitemapOutput
--- FAIL: TestSitemapOutput (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x660933]
 
goroutine 3538 [running]:
testing.func·006()
	c:/go/src/testing/testing.go:441 +0x188
github.com/spf13/afero.(*MemMapFs).registerWithParent(0xc082582fa0, 0x1679a0, 0xc082103c70)
	C:/GOPATH/src/github.com/spf13/afero/memmap.go:143 +0x463
github.com/spf13/afero.(*MemMapFs).Create(0xc082582fa0, 0xc0828368ba, 0x1, 0x0, 0x0, 0x0, 0x0)
	C:/GOPATH/src/github.com/spf13/afero/memmap.go:93 +0x19a
github.com/spf13/hugo/helpers.WriteToDisk(0xc0828368ba, 0x1, 0x167b60, 0xc082367500, 0x162ca0, 0xc082582fa0, 0x0, 0x0)
	C:/GOPATH/src/github.com/spf13/hugo/helpers/path.go:555 +0x198
github.com/spf13/hugo/target.(*Filesystem).Publish(0xc08232a5c0, 0x0, 0x0, 0x167b60, 0xc082367500, 0x0, 0x0)
	C:/GOPATH/src/github.com/spf13/hugo/target/file.go:39 +0xce
github.com/spf13/hugo/hugolib.(*Site).WriteDestFile(0xc082864d20, 0x0, 0x0, 0x167b60, 0xc082367500, 0x0, 0x0)
	github.com/spf13/hugo/hugolib/_test/_obj_test/site.go:1946 +0x1e8
github.com/spf13/hugo/hugolib.(*Site).renderAndWriteXML(0xc082864d20, 0xb4def0, 0xc, 0x0, 0x0, 0xace0c0, 0xc0827c8c60, 0xc0827cb290, 0x3, 0x3, ...)
	github.com/spf13/hugo/hugolib/_test/_obj_test/site.go:1772 +0x40a
github.com/spf13/hugo/hugolib.(*Site).RenderHomePage(0xc082864d20, 0x0, 0x0)
	github.com/spf13/hugo/hugolib/_test/_obj_test/site.go:1621 +0x83f
github.com/spf13/hugo/hugolib.TestSitemapOutput(0xc0825ea090)
	C:/GOPATH/src/github.com/spf13/hugo/hugolib/sitemap_test.go:50 +0x477
testing.tRunner(0xc0825ea090, 0xe86160)
	c:/go/src/testing/testing.go:447 +0xc6
created by testing.RunTests
	c:/go/src/testing/testing.go:555 +0xa92
 
goroutine 1 [chan receive]:
testing.RunTests(0xc6cbc8, 0xe85440, 0x8e, 0x8e, 0xe88f01)
	c:/go/src/testing/
```

Haven't looked closer.

**Comment by spf13** [comment]
I'll investigate. Thanks.

**Comment by spf13** [comment]
I believe this commit is the cause 

https://github.com/spf13/afero/commit/3de0cfae066fec719368331423c835a8b682c92d

cc @mbertschler

**Comment by mbertschler** [comment]
Thanks to this I discovered this problem #20 
I'm trying to make this work properly.

**Comment by bep** [comment]
@mbertschler thanks for the super-fast response ... the Hugo build is green now!
