### ISSUE TITLE
BasePathFs.RealPath panics on empty base path

### ISSUE THREAD

**Issue by bep** [spf13/afero#77]
An `ErrNotExist` would be better, maybe -- or maybe return an error on construction. This sounds like a bug in Go's stdlib, I'll report an issue. Not sure what an empty file path is supposed to work as.

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x1cf9af]

goroutine 227 [running]:
panic(0x723440, 0xc82000a1b0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.tRunner.func1(0xc8202e93b0)
	/usr/local/go/src/testing/testing.go:467 +0x192
panic(0x723440, 0xc82000a1b0)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/spf13/afero.(*BasePathFs).RealPath(0x0, 0x7f3a68, 0x1, 0x0, 0x0, 0x0, 0x0)
	/Users/bep/go/src/github.com/spf13/afero/basepath.go:37 +0x2ff
github.com/spf13/afero.(*BasePathFs).Open(0x0, 0x7f3a68, 0x1, 0x0, 0x0, 0x0, 0x0)
	/Users/bep/go/src/github.com/spf13/afero/basepath.go:118 +0x5b
github.com/spf13/afero.ReadFile(0x18c42c0, 0x0, 0x7f3a68, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/bep/go/src/github.com/spf13/afero/ioutil.go:65 +0x7f
``

**Comment by bep** [comment]
My bad, it was BasePathFs that was nil ... hmm...
